apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot-mgmt-service
spec:
  type: NodePort
  selector:
    app: ai-chatbot-mgmt
  ports:
    - name: http
      port: 80          # service port
      targetPort: 5000  # Flask container port
      nodePort: 30080   # external port on the node
